// Categorized emoji data. Each item is [emoji, keywords] — keywords power search.

export interface EmojiCategory {
  name: string;
  icon: string;
  items: [string, string][];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "Smileys",
    icon: "😀",
    items: [
      ["😀", "grin smile happy face"], ["😃", "smile happy joy face"], ["😄", "smile happy laugh"],
      ["😁", "beam grin smile"], ["😆", "laugh haha satisfied"], ["😅", "sweat laugh nervous"],
      ["🤣", "rofl rolling laugh lol"], ["😂", "joy laugh cry tears lol"], ["🙂", "slight smile"],
      ["🙃", "upside down silly"], ["😉", "wink flirt"], ["😊", "blush smile happy"],
      ["😇", "innocent angel halo"], ["🥰", "love hearts adore"], ["😍", "heart eyes love"],
      ["🤩", "star struck excited wow"], ["😘", "kiss blow love"], ["😗", "kiss"],
      ["😋", "yum tasty tongue"], ["😛", "tongue playful"], ["😜", "wink tongue silly"],
      ["🤪", "zany crazy goofy"], ["😝", "tongue squint"], ["🤑", "money mouth rich"],
      ["🤗", "hug hands"], ["🤭", "giggle hand mouth oops"], ["🤫", "shush quiet silent"],
      ["🤔", "thinking hmm think"], ["🤐", "zipper mouth quiet"], ["🤨", "raised eyebrow suspicious"],
      ["😐", "neutral meh"], ["😑", "expressionless blank"], ["😶", "no mouth silent"],
      ["😏", "smirk sly"], ["😒", "unamused annoyed"], ["🙄", "eye roll whatever"],
      ["😬", "grimace awkward"], ["😌", "relieved calm"], ["😔", "sad pensive down"],
      ["😪", "sleepy tired"], ["🤤", "drool"], ["😴", "sleep zzz tired"],
      ["😷", "mask sick ill"], ["🤒", "sick thermometer fever"], ["🤕", "hurt bandage injured"],
      ["🤢", "nausea sick gross"], ["🤮", "vomit puke sick"], ["🤧", "sneeze sick tissue"],
      ["🥵", "hot heat sweat"], ["🥶", "cold freezing"], ["😵", "dizzy ko"],
      ["🤯", "mind blown shocked"], ["🤠", "cowboy hat"], ["🥳", "party celebrate hat"],
      ["😎", "cool sunglasses"], ["🤓", "nerd glasses geek"], ["🧐", "monocle inspect"],
      ["😕", "confused"], ["😟", "worried"], ["🙁", "frown sad"], ["☹️", "frown sad"],
      ["😮", "wow surprised oh"], ["😲", "astonished shocked"], ["🥺", "pleading puppy eyes"],
      ["😢", "cry sad tear"], ["😭", "sob cry bawl"], ["😱", "scream fear shocked"],
      ["😖", "confounded"], ["😞", "disappointed sad"], ["😩", "weary tired"],
      ["😫", "tired exhausted"], ["🥱", "yawn bored tired"], ["😤", "huff steam angry"],
      ["😡", "angry mad rage red"], ["😠", "angry mad"], ["🤬", "swear curse angry"],
      ["😈", "devil smile evil"], ["👿", "devil angry imp"], ["💀", "skull dead"],
      ["💩", "poop crap"], ["🤡", "clown"], ["👻", "ghost boo"], ["👽", "alien ufo"],
      ["🤖", "robot bot"], ["😺", "cat smile"], ["😻", "cat heart eyes love"],
    ],
  },
  {
    name: "People",
    icon: "👋",
    items: [
      ["👋", "wave hello hi bye"], ["🤚", "raised hand back"], ["✋", "hand stop high five"],
      ["🖖", "vulcan spock"], ["👌", "ok perfect"], ["🤏", "pinch small"],
      ["✌️", "victory peace"], ["🤞", "fingers crossed luck"], ["🤟", "love you hand"],
      ["🤘", "rock horns"], ["🤙", "call me shaka hang loose"], ["👈", "point left"],
      ["👉", "point right"], ["👆", "point up"], ["👇", "point down"], ["☝️", "point up index"],
      ["👍", "thumbs up like yes good"], ["👎", "thumbs down dislike no bad"], ["✊", "fist raised"],
      ["👊", "fist bump punch"], ["🤛", "fist left"], ["🤜", "fist right"],
      ["👏", "clap applause"], ["🙌", "raise hands celebrate praise"], ["👐", "open hands"],
      ["🤲", "palms up pray"], ["🙏", "pray thanks please namaste"], ["✍️", "write hand"],
      ["💅", "nails manicure"], ["💪", "muscle strong flex"], ["🦵", "leg"], ["🦶", "foot"],
      ["👂", "ear listen"], ["👃", "nose smell"], ["🧠", "brain mind"], ["👀", "eyes look"],
      ["👁️", "eye"], ["👅", "tongue"], ["👄", "lips mouth"], ["💋", "kiss lips"],
      ["👶", "baby"], ["🧒", "child kid"], ["👦", "boy"], ["👧", "girl"], ["🧑", "person adult"],
      ["👨", "man"], ["👩", "woman"], ["🧓", "old person elder"], ["👴", "old man grandpa"],
      ["👵", "old woman grandma"], ["🙅", "no gesture stop"], ["🙆", "ok gesture"],
      ["💁", "info desk sassy"], ["🙋", "raise hand question"], ["🙇", "bow sorry"],
      ["🤦", "facepalm"], ["🤷", "shrug dunno"], ["👮", "police cop"], ["🕵️", "detective spy"],
      ["💂", "guard"], ["👷", "construction worker"], ["🤴", "prince"], ["👸", "princess"],
      ["🧕", "headscarf hijab"], ["🤵", "tuxedo groom"], ["👰", "bride veil"], ["🤰", "pregnant"],
      ["👼", "angel baby"], ["🎅", "santa christmas"], ["🤶", "mrs claus"], ["🦸", "superhero"],
      ["🦹", "supervillain"], ["🧙", "wizard mage"], ["🧚", "fairy"], ["🧛", "vampire"],
      ["🧜", "mermaid merman"], ["🧞", "genie"], ["🧟", "zombie"], ["💆", "massage spa"],
      ["💇", "haircut salon"], ["🚶", "walk pedestrian"], ["🏃", "run runner"], ["💃", "dance woman"],
      ["🕺", "dance man"], ["🧘", "yoga meditate"], ["👯", "dancers bunny"],
    ],
  },
  {
    name: "Animals",
    icon: "🐶",
    items: [
      ["🐶", "dog puppy"], ["🐱", "cat kitten"], ["🐭", "mouse"], ["🐹", "hamster"],
      ["🐰", "rabbit bunny"], ["🦊", "fox"], ["🐻", "bear"], ["🐼", "panda"],
      ["🐨", "koala"], ["🐯", "tiger"], ["🦁", "lion"], ["🐮", "cow"], ["🐷", "pig"],
      ["🐸", "frog"], ["🐵", "monkey"], ["🙈", "see no evil monkey"], ["🙉", "hear no evil monkey"],
      ["🙊", "speak no evil monkey"], ["🐒", "monkey"], ["🐔", "chicken"], ["🐧", "penguin"],
      ["🐦", "bird"], ["🐤", "chick baby"], ["🦆", "duck"], ["🦅", "eagle"], ["🦉", "owl"],
      ["🦇", "bat"], ["🐺", "wolf"], ["🐗", "boar"], ["🐴", "horse"], ["🦄", "unicorn"],
      ["🐝", "bee honey"], ["🐛", "bug caterpillar"], ["🦋", "butterfly"], ["🐌", "snail"],
      ["🐞", "ladybug"], ["🐜", "ant"], ["🕷️", "spider"], ["🦂", "scorpion"], ["🐢", "turtle"],
      ["🐍", "snake"], ["🦎", "lizard"], ["🦖", "trex dinosaur"], ["🦕", "dinosaur sauropod"],
      ["🐙", "octopus"], ["🦑", "squid"], ["🦐", "shrimp"], ["🦀", "crab"], ["🐠", "fish tropical"],
      ["🐟", "fish"], ["🐬", "dolphin"], ["🐳", "whale spout"], ["🐋", "whale"], ["🦈", "shark"],
      ["🐊", "crocodile"], ["🐆", "leopard"], ["🦓", "zebra"], ["🦍", "gorilla"], ["🐘", "elephant"],
      ["🦏", "rhino"], ["🐪", "camel"], ["🦒", "giraffe"], ["🐃", "buffalo"], ["🐄", "cow"],
      ["🐎", "horse racing"], ["🐖", "pig"], ["🐑", "sheep"], ["🐐", "goat"], ["🦌", "deer"],
      ["🐕", "dog"], ["🐈", "cat"], ["🐓", "rooster"], ["🦃", "turkey"], ["🦚", "peacock"],
      ["🦜", "parrot"], ["🦢", "swan"], ["🕊️", "dove peace"], ["🐇", "rabbit"], ["🦝", "raccoon"],
      ["🦔", "hedgehog"], ["🐉", "dragon"], ["🌵", "cactus"], ["🎄", "christmas tree"],
      ["🌲", "evergreen tree"], ["🌳", "tree"], ["🌴", "palm tree"], ["🌱", "seedling sprout"],
      ["🌿", "herb leaf"], ["☘️", "shamrock"], ["🍀", "clover luck four leaf"], ["🍁", "maple leaf fall"],
      ["🍂", "leaves fall autumn"], ["🍄", "mushroom"], ["🌷", "tulip flower"], ["🌹", "rose flower"],
      ["🌺", "hibiscus flower"], ["🌸", "cherry blossom flower"], ["🌻", "sunflower"], ["🌼", "daisy flower"],
      ["⭐", "star"], ["🌟", "glowing star sparkle"], ["✨", "sparkles shiny"], ["⚡", "lightning bolt"],
      ["🔥", "fire flame lit hot"], ["🌈", "rainbow"], ["☀️", "sun sunny"], ["☁️", "cloud"],
      ["❄️", "snowflake cold"], ["☃️", "snowman"], ["💧", "droplet water"], ["🌊", "wave ocean water"],
    ],
  },
  {
    name: "Food",
    icon: "🍔",
    items: [
      ["🍏", "green apple"], ["🍎", "apple red"], ["🍐", "pear"], ["🍊", "orange tangerine"],
      ["🍋", "lemon"], ["🍌", "banana"], ["🍉", "watermelon"], ["🍇", "grapes"], ["🍓", "strawberry"],
      ["🍒", "cherries"], ["🍑", "peach"], ["🥭", "mango"], ["🍍", "pineapple"], ["🥥", "coconut"],
      ["🥝", "kiwi"], ["🍅", "tomato"], ["🍆", "eggplant aubergine"], ["🥑", "avocado"],
      ["🥦", "broccoli"], ["🥒", "cucumber"], ["🌶️", "pepper spicy hot chili"], ["🌽", "corn"],
      ["🥕", "carrot"], ["🧄", "garlic"], ["🧅", "onion"], ["🥔", "potato"], ["🍠", "sweet potato"],
      ["🥐", "croissant"], ["🥯", "bagel"], ["🍞", "bread"], ["🥖", "baguette"], ["🥨", "pretzel"],
      ["🧀", "cheese"], ["🥚", "egg"], ["🍳", "fried egg cooking"], ["🥞", "pancakes"],
      ["🧇", "waffle"], ["🥓", "bacon"], ["🥩", "steak meat"], ["🍗", "poultry chicken leg"],
      ["🍖", "meat bone"], ["🌭", "hot dog"], ["🍔", "burger hamburger"], ["🍟", "fries"],
      ["🍕", "pizza"], ["🥪", "sandwich"], ["🌮", "taco"], ["🌯", "burrito"], ["🥗", "salad"],
      ["🍝", "spaghetti pasta"], ["🍜", "ramen noodles"], ["🍲", "stew soup pot"], ["🍛", "curry rice"],
      ["🍣", "sushi"], ["🍱", "bento box"], ["🥟", "dumpling"], ["🍤", "shrimp fried tempura"],
      ["🍚", "rice"], ["🍥", "fish cake"], ["🥮", "moon cake"], ["🍢", "oden"], ["🍡", "dango"],
      ["🍧", "shaved ice"], ["🍨", "ice cream"], ["🍦", "soft serve ice cream"], ["🥧", "pie"],
      ["🧁", "cupcake"], ["🍰", "cake slice shortcake"], ["🎂", "birthday cake"], ["🍮", "custard pudding"],
      ["🍭", "lollipop candy"], ["🍬", "candy sweet"], ["🍫", "chocolate"], ["🍿", "popcorn"],
      ["🍩", "donut doughnut"], ["🍪", "cookie"], ["🌰", "chestnut"], ["🥜", "peanuts nuts"],
      ["🍯", "honey"], ["🥛", "milk glass"], ["🍼", "baby bottle milk"], ["☕", "coffee tea hot"],
      ["🍵", "tea green"], ["🧃", "juice box"], ["🥤", "soda cup drink"], ["🍶", "sake"],
      ["🍺", "beer"], ["🍻", "beers cheers"], ["🥂", "champagne cheers toast"], ["🍷", "wine"],
      ["🥃", "whiskey"], ["🍸", "cocktail martini"], ["🍹", "tropical drink"], ["🍾", "champagne bottle"],
      ["🥄", "spoon"], ["🍴", "fork knife"], ["🍽️", "plate dining"], ["🥢", "chopsticks"], ["🧂", "salt"],
    ],
  },
  {
    name: "Activities",
    icon: "⚽",
    items: [
      ["⚽", "soccer football"], ["🏀", "basketball"], ["🏈", "american football"], ["⚾", "baseball"],
      ["🥎", "softball"], ["🎾", "tennis"], ["🏐", "volleyball"], ["🏉", "rugby"], ["🥏", "frisbee"],
      ["🎱", "pool 8 ball billiards"], ["🏓", "ping pong table tennis"], ["🏸", "badminton"],
      ["🏒", "hockey ice"], ["🏑", "field hockey"], ["🥍", "lacrosse"], ["🏏", "cricket"],
      ["⛳", "golf"], ["🪁", "kite"], ["🏹", "bow arrow archery"], ["🎣", "fishing"],
      ["🥊", "boxing glove"], ["🥋", "martial arts karate"], ["🎽", "running shirt"], ["🛹", "skateboard"],
      ["⛸️", "ice skate"], ["🥌", "curling"], ["🎿", "ski"], ["🏂", "snowboard"], ["🏋️", "weight lifting gym"],
      ["🤼", "wrestling"], ["🤸", "cartwheel gymnastics"], ["⛹️", "basketball player"], ["🤺", "fencing"],
      ["🏌️", "golfer"], ["🏇", "horse racing"], ["🧘", "yoga meditation"], ["🏄", "surf"],
      ["🏊", "swim"], ["🚣", "rowing boat"], ["🧗", "climbing"], ["🚵", "mountain biking"],
      ["🚴", "cycling bike"], ["🏆", "trophy win champion"], ["🥇", "gold medal first"],
      ["🥈", "silver medal second"], ["🥉", "bronze medal third"], ["🏅", "medal"], ["🎖️", "military medal"],
      ["🎗️", "ribbon"], ["🎫", "ticket"], ["🎪", "circus tent"], ["🤹", "juggling"], ["🎭", "theater masks"],
      ["🎨", "art paint palette"], ["🎬", "movie clapper film"], ["🎤", "mic sing karaoke"],
      ["🎧", "headphones music"], ["🎼", "music score"], ["🎹", "piano keyboard"], ["🥁", "drum"],
      ["🎷", "saxophone"], ["🎺", "trumpet"], ["🎸", "guitar"], ["🎻", "violin"], ["🎲", "dice game"],
      ["♟️", "chess pawn"], ["🎯", "dart target bullseye"], ["🎳", "bowling"], ["🎮", "video game controller"],
      ["🎰", "slot machine gamble"], ["🧩", "puzzle piece"],
    ],
  },
  {
    name: "Travel",
    icon: "✈️",
    items: [
      ["🚗", "car red"], ["🚕", "taxi"], ["🚙", "suv car"], ["🚌", "bus"], ["🏎️", "race car"],
      ["🚓", "police car"], ["🚑", "ambulance"], ["🚒", "fire truck"], ["🚐", "minivan"],
      ["🚚", "truck delivery"], ["🚛", "lorry truck"], ["🚜", "tractor"], ["🛴", "scooter kick"],
      ["🚲", "bicycle bike"], ["🛵", "scooter motor"], ["🏍️", "motorcycle"], ["🚨", "siren light police"],
      ["🚍", "bus oncoming"], ["🚘", "car oncoming"], ["🚖", "taxi oncoming"], ["🚡", "aerial tram"],
      ["🚠", "mountain cableway"], ["🚟", "suspension railway"], ["🚃", "railway car"], ["🚋", "tram"],
      ["🚝", "monorail"], ["🚄", "bullet train shinkansen"], ["🚅", "bullet train"], ["🚈", "light rail"],
      ["🚂", "locomotive steam train"], ["🚆", "train"], ["🚇", "metro subway"], ["🚊", "tram"],
      ["🚉", "station train"], ["✈️", "airplane plane flight"], ["🛫", "departure takeoff"],
      ["🛬", "arrival landing"], ["💺", "seat"], ["🛰️", "satellite"], ["🚀", "rocket launch space"],
      ["🛸", "ufo flying saucer"], ["🚁", "helicopter"], ["⛵", "sailboat"], ["🚤", "speedboat"],
      ["🛳️", "cruise ship"], ["⛴️", "ferry"], ["🚢", "ship"], ["⚓", "anchor"], ["⛽", "fuel gas station"],
      ["🚧", "construction barrier"], ["🚦", "traffic light"], ["🚥", "traffic light horizontal"],
      ["🗺️", "map world"], ["🗿", "moai statue"], ["🗽", "statue of liberty"], ["🗼", "tokyo tower"],
      ["🏰", "castle"], ["🏯", "japanese castle"], ["🏟️", "stadium"], ["🎡", "ferris wheel"],
      ["🎢", "roller coaster"], ["🎠", "carousel"], ["⛲", "fountain"], ["🏖️", "beach umbrella"],
      ["🏝️", "desert island"], ["🌋", "volcano"], ["⛰️", "mountain"], ["🏔️", "snow mountain"],
      ["🏕️", "camping tent"], ["🏠", "house home"], ["🏡", "house garden"], ["🏢", "office building"],
      ["🏬", "department store"], ["🏥", "hospital"], ["🏦", "bank"], ["🏨", "hotel"], ["🏫", "school"],
      ["⛪", "church"], ["🕌", "mosque"], ["🛕", "hindu temple"], ["🌁", "foggy"], ["🌃", "night stars city"],
      ["🌉", "bridge night"], ["🌅", "sunrise"], ["🌆", "city dusk sunset"], ["🌇", "sunset city"],
      ["🎇", "fireworks sparkler"], ["🎆", "fireworks"],
    ],
  },
  {
    name: "Objects",
    icon: "💡",
    items: [
      ["⌚", "watch time"], ["📱", "phone mobile smartphone"], ["💻", "laptop computer"],
      ["⌨️", "keyboard"], ["🖥️", "desktop computer monitor"], ["🖨️", "printer"], ["🖱️", "mouse computer"],
      ["💽", "minidisc"], ["💾", "floppy save disk"], ["💿", "cd disk"], ["📀", "dvd"], ["📷", "camera photo"],
      ["📸", "camera flash"], ["📹", "video camera"], ["🎥", "movie camera film"], ["📽️", "projector film"],
      ["📞", "phone receiver call"], ["☎️", "telephone"], ["📟", "pager"], ["📠", "fax"], ["📺", "tv television"],
      ["📻", "radio"], ["🎙️", "microphone studio"], ["⏱️", "stopwatch timer"], ["⏰", "alarm clock"],
      ["⌛", "hourglass time"], ["⏳", "hourglass flowing"], ["📡", "satellite antenna signal"],
      ["🔋", "battery"], ["🔌", "plug power electric"], ["💡", "light bulb idea"], ["🔦", "flashlight torch"],
      ["🕯️", "candle"], ["🧯", "fire extinguisher"], ["💸", "money flying cash"], ["💵", "dollar money"],
      ["💴", "yen money"], ["💶", "euro money"], ["💷", "pound money"], ["💰", "money bag"],
      ["💳", "credit card"], ["💎", "gem diamond"], ["⚖️", "scales balance justice"], ["🧰", "toolbox"],
      ["🔧", "wrench tool"], ["🔨", "hammer tool"], ["🛠️", "tools hammer wrench"], ["⛏️", "pick mining"],
      ["🔩", "nut bolt screw"], ["⚙️", "gear settings cog"], ["🧱", "brick"], ["⛓️", "chains"],
      ["🧲", "magnet"], ["🔫", "gun water pistol"], ["💣", "bomb"], ["🧨", "firecracker dynamite"],
      ["🪓", "axe"], ["🔪", "knife cut"], ["🗡️", "dagger sword"], ["🛡️", "shield"], ["🚬", "cigarette smoke"],
      ["⚰️", "coffin"], ["🏺", "amphora jar"], ["🔮", "crystal ball fortune"], ["📿", "prayer beads"],
      ["🧿", "nazar amulet"], ["💈", "barber pole"], ["⚗️", "alembic chemistry"], ["🔭", "telescope"],
      ["🔬", "microscope"], ["💊", "pill medicine"], ["💉", "syringe shot vaccine"], ["🩹", "bandage"],
      ["🌡️", "thermometer temperature"], ["🧬", "dna"], ["🦠", "microbe germ virus"], ["🧪", "test tube"],
      ["🧹", "broom sweep"], ["🧻", "toilet paper roll"], ["🚽", "toilet"], ["🚿", "shower"],
      ["🛁", "bath tub"], ["🧼", "soap"], ["🧴", "lotion bottle"], ["🔑", "key"], ["🗝️", "old key"],
      ["🚪", "door"], ["🛋️", "couch sofa"], ["🛏️", "bed"], ["🧸", "teddy bear toy"], ["🖼️", "framed picture"],
      ["🛍️", "shopping bags"], ["🛒", "shopping cart trolley"], ["🎁", "gift present"], ["🎈", "balloon"],
      ["🎀", "ribbon bow"], ["🎊", "confetti ball"], ["🎉", "party popper tada celebrate"],
      ["✉️", "envelope email mail"], ["📧", "email"], ["📦", "package box"], ["📫", "mailbox"],
      ["✏️", "pencil write"], ["✒️", "pen nib"], ["🖊️", "pen"], ["📝", "memo note write"],
      ["📁", "folder file"], ["📅", "calendar date"], ["📆", "calendar tear off"], ["📊", "bar chart"],
      ["📈", "chart up growth"], ["📉", "chart down loss"], ["📋", "clipboard"], ["📌", "pushpin"],
      ["📎", "paperclip"], ["✂️", "scissors cut"], ["🗑️", "trash bin delete"], ["🔒", "lock locked"],
      ["🔓", "unlock open"], ["🔐", "lock key secure"],
    ],
  },
  {
    name: "Symbols",
    icon: "❤️",
    items: [
      ["❤️", "red heart love"], ["🧡", "orange heart"], ["💛", "yellow heart"], ["💚", "green heart"],
      ["💙", "blue heart"], ["💜", "purple heart"], ["🖤", "black heart"], ["🤍", "white heart"],
      ["🤎", "brown heart"], ["💔", "broken heart breakup"], ["❣️", "heart exclamation"],
      ["💕", "two hearts love"], ["💞", "revolving hearts"], ["💓", "beating heart"], ["💗", "growing heart"],
      ["💖", "sparkling heart"], ["💘", "cupid arrow heart"], ["💝", "heart gift ribbon"], ["💟", "heart decoration"],
      ["☮️", "peace"], ["✝️", "cross christian"], ["☪️", "star crescent islam"], ["🕉️", "om hindu"],
      ["✡️", "star of david jewish"], ["☯️", "yin yang"], ["⚛️", "atom science"], ["♈", "aries zodiac"],
      ["♉", "taurus zodiac"], ["♊", "gemini zodiac"], ["♋", "cancer zodiac"], ["♌", "leo zodiac"],
      ["♍", "virgo zodiac"], ["♎", "libra zodiac"], ["♏", "scorpio zodiac"], ["♐", "sagittarius zodiac"],
      ["♑", "capricorn zodiac"], ["♒", "aquarius zodiac"], ["♓", "pisces zodiac"], ["⛎", "ophiuchus zodiac"],
      ["🔯", "six pointed star"], ["☢️", "radioactive"], ["☣️", "biohazard"], ["✴️", "eight pointed star"],
      ["🆚", "versus vs"], ["💯", "hundred 100 perfect"], ["💢", "anger angry"], ["♨️", "hot springs steam"],
      ["🚫", "prohibited no"], ["⭕", "circle o"], ["🛑", "stop sign"], ["⛔", "no entry"],
      ["📛", "name badge"], ["❌", "x cross wrong no"], ["❗", "exclamation important"], ["❓", "question"],
      ["‼️", "double exclamation"], ["⁉️", "exclamation question"], ["⚠️", "warning caution"],
      ["🔰", "beginner"], ["♻️", "recycle"], ["✅", "check mark green yes done"], ["✔️", "check mark yes"],
      ["☑️", "checkbox checked"], ["❎", "cross mark green"], ["🌐", "globe web internet"],
      ["Ⓜ️", "metro m"], ["🔵", "blue circle"], ["🔴", "red circle"], ["🟠", "orange circle"],
      ["🟡", "yellow circle"], ["🟢", "green circle"], ["🟣", "purple circle"], ["⚫", "black circle"],
      ["⚪", "white circle"], ["🟤", "brown circle"], ["🔺", "red triangle up"], ["🔻", "red triangle down"],
      ["🔶", "orange diamond"], ["🔷", "blue diamond"], ["🟥", "red square"], ["🟧", "orange square"],
      ["🟨", "yellow square"], ["🟩", "green square"], ["🟦", "blue square"], ["🟪", "purple square"],
      ["⬛", "black square"], ["⬜", "white square"], ["🔔", "bell notification"], ["🔕", "bell mute"],
      ["📢", "loudspeaker announce"], ["📣", "megaphone cheer"], ["💬", "speech bubble chat"],
      ["💭", "thought bubble"], ["🗯️", "anger speech bubble"], ["♠️", "spades card"], ["♣️", "clubs card"],
      ["♥️", "hearts card"], ["♦️", "diamonds card"], ["🃏", "joker card"], ["▶️", "play"],
      ["⏸️", "pause"], ["⏹️", "stop"], ["⏭️", "next track"], ["⏮️", "previous track"], ["⏩", "fast forward"],
      ["⏪", "rewind"], ["🔀", "shuffle"], ["🔁", "repeat loop"], ["🔂", "repeat one"], ["➡️", "right arrow"],
      ["⬅️", "left arrow"], ["⬆️", "up arrow"], ["⬇️", "down arrow"], ["🔝", "top up"], ["🎵", "music note"],
      ["🎶", "music notes"], ["➕", "plus add"], ["➖", "minus subtract"], ["➗", "divide"], ["✖️", "multiply"],
      ["♾️", "infinity"], ["💲", "dollar sign"], ["™️", "trademark"], ["©️", "copyright"], ["®️", "registered"],
      ["✔️", "tick"], ["🆗", "ok button"], ["🆕", "new"], ["🆓", "free"], ["🆒", "cool"], ["🆙", "up"],
    ],
  },
  {
    name: "Flags",
    icon: "🏁",
    items: [
      ["🏳️", "white flag surrender"], ["🏴", "black flag"], ["🏁", "checkered flag finish race"],
      ["🚩", "triangular flag red"], ["🏳️‍🌈", "rainbow pride flag lgbt"], ["🏴‍☠️", "pirate flag jolly roger"],
      ["🇺🇸", "united states usa america flag"], ["🇬🇧", "united kingdom uk britain flag"],
      ["🇨🇦", "canada flag"], ["🇦🇺", "australia flag"], ["🇩🇪", "germany flag deutschland"],
      ["🇫🇷", "france flag"], ["🇪🇸", "spain flag espana"], ["🇮🇹", "italy flag italia"],
      ["🇯🇵", "japan flag nippon"], ["🇰🇷", "south korea flag"], ["🇨🇳", "china flag"],
      ["🇮🇳", "india flag"], ["🇧🇷", "brazil flag brasil"], ["🇷🇺", "russia flag"],
      ["🇲🇽", "mexico flag"], ["🇳🇱", "netherlands flag holland"], ["🇸🇪", "sweden flag"],
      ["🇳🇴", "norway flag"], ["🇩🇰", "denmark flag"], ["🇫🇮", "finland flag"], ["🇵🇱", "poland flag"],
      ["🇵🇹", "portugal flag"], ["🇬🇷", "greece flag"], ["🇨🇭", "switzerland flag swiss"],
      ["🇦🇹", "austria flag"], ["🇧🇪", "belgium flag"], ["🇮🇪", "ireland flag"], ["🇳🇿", "new zealand flag"],
      ["🇿🇦", "south africa flag"], ["🇦🇷", "argentina flag"], ["🇨🇱", "chile flag"], ["🇨🇴", "colombia flag"],
      ["🇵🇪", "peru flag"], ["🇹🇷", "turkey flag"], ["🇸🇦", "saudi arabia flag"], ["🇦🇪", "uae emirates flag"],
      ["🇮🇱", "israel flag"], ["🇪🇬", "egypt flag"], ["🇹🇭", "thailand flag"], ["🇻🇳", "vietnam flag"],
      ["🇵🇭", "philippines flag"], ["🇮🇩", "indonesia flag"], ["🇲🇾", "malaysia flag"], ["🇸🇬", "singapore flag"],
      ["🇭🇰", "hong kong flag"], ["🇹🇼", "taiwan flag"], ["🇺🇦", "ukraine flag"], ["🇨🇿", "czech flag"],
      ["🇭🇺", "hungary flag"], ["🇷🇴", "romania flag"],
    ],
  },
];

// Flat lookup list for quick paste / fallback.
export const ALL_EMOJI_ITEMS: [string, string][] = EMOJI_CATEGORIES.flatMap((c) => c.items);

// Skin-tone modifiers (Fitzpatrick) + label.
export const SKIN_TONES: { tone: string; label: string }[] = [
  { tone: "", label: "Default" },
  { tone: "\u{1F3FB}", label: "Light" },
  { tone: "\u{1F3FC}", label: "Medium-light" },
  { tone: "\u{1F3FD}", label: "Medium" },
  { tone: "\u{1F3FE}", label: "Medium-dark" },
  { tone: "\u{1F3FF}", label: "Dark" },
];

// Base emojis that accept a skin-tone modifier (hands + single people).
export const TONEABLE = new Set<string>([
  "👋", "🤚", "✋", "🖖", "👌", "🤏", "✌️", "🤞", "🤟", "🤘", "🤙",
  "👈", "👉", "👆", "☝️", "👍", "👎", "✊", "👊", "🤛", "🤜", "👏",
  "🙌", "👐", "🤲", "🙏", "✍️", "💅", "💪", "🦵", "🦶", "👂", "👃",
  "👶", "🧒", "👦", "👧", "🧑", "👨", "👩", "🧓", "👴", "👵",
  "🙅", "🙆", "💁", "🙋", "🙇", "🤦", "🤷", "👮", "🕵️", "💂", "👷",
  "🤴", "👸", "🧕", "🤵", "👰", "🤰", "👼", "🎅", "🤶", "🦸", "🦹",
  "🧙", "🧚", "🧛", "🧜", "💆", "💇", "🚶", "🏃", "💃", "🕺", "🧘",
  "🏄", "🏊", "🚣", "🧗", "🚵", "🚴", "🏌️", "🏋️", "🤸", "⛹️", "🏇",
]);

/** Apply a skin tone to an emoji if it supports one. */
export function applyTone(emoji: string, tone: string): string {
  if (!tone || !TONEABLE.has(emoji)) return emoji;
  // Tone modifier replaces a trailing emoji variation selector (FE0F).
  return emoji.replace(/️$/, "") + tone;
}
